### ISSUE TITLE
CompileSwift failed (Need AVPlayer update from Swift3 to Swift4)

### ISSUE THREAD

**Issue by ghensto** [LJaraCastillo/native_video_view#10]
/Users/kaiser/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/ios/Classes/strategies/PhotoPermissionStrategy.m:39:13: warning: enumeration value 'PHAuthorizationStatusLimited' not handled in switch [-Wswitch]
        switch (authorizationStatus) {
                ^
    /Users/kaiser/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/ios/Classes/strategies/PhotoPermissionStrategy.m:39:13: note: add missing switch cases
        switch (authorizationStatus) {
                ^
    1 warning generated.
    1 warning generated.
    Command CompileSwift failed with a nonzero exit code
    /Users/kaiser/.pub-cache/hosted/pub.dartlang.org/native_video_view-0.3.0/ios/Classes/NativeVideoViewController.swift:131:65: error: 'AVAudioSessionCategoryAmbient' has been renamed to 'AVAudioSession.Category.ambient'
                    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryAmbient)
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                    AVAudioSession.Category.ambient
    AVFoundation.AVAudioSessionCategoryAmbient:3:12: note: 'AVAudioSessionCategoryAmbient' was obsoleted in Swift 3
    public let AVAudioSessionCategoryAmbient: AVAudioSession.Category
               ^
    /Users/kaiser/.pub-cache/hosted/pub.dartlang.org/native_video_view-0.3.0/ios/Classes/NativeVideoViewController.swift:133:65: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
                    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                    AVAudioSession.Category.playback
    AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
    public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
               ^
    /Users/kaiser/.pub-cache/hosted/pub.dartlang.org/native_video_view-0.3.0/ios/Classes/VideoView.swift:90:35: error: 'kCMTimeZero' has been renamed to 'CMTime.zero'
                self.player?.seek(to: kCMTimeZero)
                                      ^~~~~~~~~~~
                                      CMTime.zero
    CoreMedia.kCMTimeZero:3:12: note: 'kCMTimeZero' was obsoleted in Swift 4.2
    public let kCMTimeZero: CMTime
               ^
    /Users/kaiser/.pub-cache/hosted/pub.dartlang.org/native_video_view-0.3.0/ios/Classes/VideoView.swift:153:45: error: missing argument labels 'value:timescale:' in call
                self.player?.seek(to: CMTimeMake(pos, 1000), toleranceBefore: kCMTimeZero, toleranceAfter: kCMTimeZero)
                                                ^
                                                 value:  timescale:

**Comment by alexandranb** [comment]
I have the same issue
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.17763.1518], locale en-US)
    • Flutter version 1.22.2
    • Framework revision 84f3d28555 (3 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

**Comment by LJaraCastillo** [comment]
Fixed in 1.0.5
