### ISSUE TITLE
'AVAudioSessionCategoryAmbient' has been renamed to 'AVAudioSession.Category.ambient'

### ISSUE THREAD

**Issue by arunpkumar92** [LJaraCastillo/native_video_view#13]
Xcode's output:

.pub-cache/hosted/pub.dartlang.org/native_video_view-0.3.0/ios/Classes/NativeVideoViewController.swift:131:65: error: 'AVAudioSessionCategoryAmbient' has been renamed to 'AVAudioSession.Category.ambient'

**Comment by Steven-Chen87** [comment]
any fix on this?

**Comment by LJaraCastillo** [comment]
Fixed in 1.0.5.
