### ISSUE TITLE
on Android seekTo moves to only seconds, not milliseconds(1100 and 1900 are same position) 

### ISSUE THREAD

**Issue by ianack** [LJaraCastillo/native_video_view#16]
on Android
when i use seekto with video controller, 1100ms and 1900ms gives same frame

**Comment by LJaraCastillo** [comment]
Tested it and it seems that is how the VideoView works.

**Comment by ianack** [comment]
Hi, i just looked in to it again and found out that when implement seekto function, use Mediaplayer like

mediaPlayer?.seekTo(position, SEEK_CLOSEST)

is better than videoview.seekTo(position)

mediaPlayer's seekto function's second parameter is very useful to find exact position of video frame.

i suggest :) thanks for library
