### ISSUE TITLE
Not work for iOS

### ISSUE THREAD

**Issue by tim-teacher** [LJaraCastillo/native_video_view#3]
.pub-cache/hosted/pub.dartlang.org/native_video_view-0.1.8/ios/Classes/VideoView.swift:90:35: error: 'kCMTimeZero' has been renamed to 'CMTime.zero'
                self.player?.seek(to: kCMTimeZero)
                                      ^~~~~~~~~~~
                                      CMTime.zero
    CoreMedia.kCMTimeZero:3:12: note: 'kCMTimeZero' was obsoleted in Swift 4.2
    public let kCMTimeZero: CMTime
               ^
.pub-cache/hosted/pub.dartlang.org/native_video_view-0.1.8/ios/Classes/VideoView.swift:149:45: error: missing argument labels 'value:timescale:' in call
                self.player?.seek(to: CMTimeMake(pos, 1000), toleranceBefore: kCMTimeZero, toleranceAfter: kCMTimeZero)
                                                ^
                                                 value:  timescale: 
.pub-cache/hosted/pub.dartlang.org/native_video_view-0.1.8/ios/Classes/VideoView.swift:202:13: warning: switch covers known cases, but 'AVPlayer.Status' may have additional unknown values, possibly added in future versions
                switch(status){
                ^
.pub-cache/hosted/pub.dartlang.org/native_video_view-0.1.8/ios/Classes/VideoView.swift:202:13: note: handle unknown values using "@unknown default"
                switch(status){

**Comment by LJaraCastillo** [comment]
Solved en v0.1.9. Thanks for the issue report.

**Comment by tim-teacher** [comment]
Thanks!
