### ISSUE TITLE
Not work on some Android devices

### ISSUE THREAD

**Issue by tim-teacher** [LJaraCastillo/native_video_view#4]
Crash on some Android devices. For exp.: it happens on  Redmi Note 7, Android 9. We use local video file.

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
keyboard_arrow_up
arrow_right
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1790)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1534)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7421)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1092)
android.view.Choreographer.doCallbacks (Choreographer.java:888)
android.view.Choreographer.doFrame (Choreographer.java:819)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1078)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:201)
android.app.ActivityThread.main (ActivityThread.java:6810)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)`

**Comment by LJaraCastillo** [comment]
I have investigated a little bit and seems that is a problem with the flutter engine. https://github.com/flutter/flutter/issues/26345
