### ISSUE TITLE
Feature request: Allow silence videos to keep background media playing

### ISSUE THREAD

**Issue by ollydixon** [LJaraCastillo/native_video_view#7]
At the moment the official Flutter video_player plugin doesn't support this.
Would be nice to have 'isSilent' option or something like this so that when music is playing in the background it doesn't pause it. 

For example a use case.
Our app plays silence instructional videos at the gym. When the user opens these videos it pauses their music; not good. :-)

**Comment by LJaraCastillo** [comment]
Gonna check how to do that.

**Comment by ollydixon** [comment]
```AVAudioSessionCategoryAmbient``` is the iOS setting

**Comment by LJaraCastillo** [comment]
Added this functionality in 0.3.0
